### ISSUE TITLE
Create a codebook for each F/U interview data frame

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_public#13]
# Overview

We need to create a codebook for each F/U interview data table after it's imported from FM Pro and cleaned (#12). We will do so using the [codebookr package](https://github.com/brad-cannell/codebookr). 

It is probably a good idea to go over each codebook with the larger team before moving on to the next one. At least for the first couple of codebooks. 

# Tasks

- [x] Create a codebook for each F/U interview data frame.
- [ ] 2023-07-10: Finalize the codebook for the participant data frame (waiting on Sunil)

**Comment by edambo** [comment]
I've created my first codebook for the APS data and I'm ready to go over it.
I have a couple of issues/ questions:

- I'm not sure what the appropriate descriptions are for the xc_lead_panel_summary_count and the xc_case_i_d variables. The descriptions currently included are placeholders.
- My title and subtitle are at the bottom and not the top of the page for some reason and I'm still working on how to fix this,

**Comment by mbcann01** [comment]
This is great, @edambo ! Enjoy your weekend and let's take a look at them on Monday. How does that sound?

**Comment by edambo** [comment]
Sounds goo, thank you!

**Comment by edambo** [comment]
Changes requested to be made to the aps codebook:
- Change dataset name from apinve to aps_inv
- Change all source info to APS
- Remove character variables, leaving only factors.
- Change the descriptions to interview questions
- Put factor variables in logical order - **they already are. Some are descending and others are ascending but they are based on the order in the interview instrument document.**
- Change column name from xc_case_i_d to xc_case_id


[data_01_aps_investigations_codebook.docx](https://github.com/brad-cannell/detect_fu_interviews_public/files/11083366/data_01_aps_investigations_codebook.docx)
[data_01_clutter_scale_codebook.docx](https://github.com/brad-cannell/detect_fu_interviews_public/files/11083365/data_01_clutter_scale_codebook.docx)
[data_01_general_health_codebook.docx](https://github.com/brad-cannell/detect_fu_interviews_public/files/11083367/data_01_general_health_codebook.docx)

**Comment by mbcann01** [comment]
Hi @edambo !

Thank you for doing this! Do you mind submitting your work as a pull request, please? And also adding in the comments that the pull request is related to issue #13. 

Thank you!
Brad

**Comment by edambo** [comment]
Good evening,

I had already also submitted a pull request on Monday. Did you not receive
one?

Ebie

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by edambo** [comment]
Oh, okay. maybe I didn't send it properly. I'll check on this.

Ebie

**Comment by mbcann01** [comment]
Hi @edambo ,

I'm looking through the codebook files now. Sorry it has taken me so long. There are a bunch of word documents in the `codebook` folder. Which ones should I be looking at? Can any of them be deleted?

Thank you!
Brad
