### ISSUE TITLE
Perform an initial analysis of LEAD panel determinations.

### ISSUE THREAD

**Issue by edambo** [brad-cannell/detect_fu_interviews_public#23]
# Overview

Create some descriptive tables. We want better to understand the results of the LEAD panel determinations.

# Task

- [x] Create a confusion matrix with DETECT initial screening as rows and DETECT LEAD determinations as columns.

**Comment by mbcann01** [comment]
Thanks, @edambo! I'm looking over the table you created I'll send you some comments directly in that Word document.
